language: perl6

perl6:
    - latest
    - '2017.05'
    - '2017.04'

install:
    - git clone https://github.com/WizardMac/ReadStat.git
    - cd ReadStat
    - ./autogen.sh
    - ./configure
    - make
    - sudo cp .libs/*.* /usr/lib
    - cd ..
